export const ALLOWED_USERS = [
  { email: 'tattoosbytomma@gmail.com', name: 'Tomma' },
  { email: 'ladyshytattoos@gmail.com', name: 'Shy' },
  { email: 'events.anatomytattoo@gmail.com', name: 'Shy' },
  { email: 'thundermadetattoos@gmail.com', name: 'Sienna' },
  { email: 'sketchu2@gmail.com', name: 'Summer' },
  { email: 'sailorsisilia@gmail.com', name: 'Sisi' },
  { email: 'info@agneshamilton.com', name: 'Agnes' },
  { email: 'meganechtattoos@gmail.com', name: 'Megan' },
  { email: 'meganechevarria96@gmail.com', name: 'Megan' },
  { email: 'jazzstahrtattoo@gmail.com', name: 'Jazz' },
  { email: 'jazzstahr@gmail.com', name: 'Jazz' },
  { email: 'appointments@drewlinden.com', name: 'Drew' },
  { email: 'drew@drewlinden.com', name: 'Drew' },
  { email: 'honeyandsass@gmail.com', name: 'Lindsay' },
  { email: 'inkdiva66@gmail.com', name: 'Anne' },
  { email: 'jaketongtattoos@gmail.com', name: 'Jake' },
  { email: 'artsofjayden@gmail.com', name: 'Jayden' },
  { email: 'jamueller01@gmail.com', name: 'Jayden' },
  { email: 'luckymalony@gmail.com', name: 'Lucky' },
  { email: 'sirjasonbarnes@gmail.com', name: 'Jason' },
  { email: 'veda.mueller.27@gmail.com', name: 'Veda' },
  { email: 'breannenorling@gmail.com', name: 'Bree' },
  { email: 'anatomytattoo@gmail.com', name: 'Tomma' },
  { email: 'mrs.annaclarke@gmail.com', name: 'Anna' },
  { email: 'admin@anatomytattoo.com', name: 'Anna' },
];

export const ALLOWED_EMAILS = new Set(ALLOWED_USERS.map(({ email }) => email.toLowerCase()));
